services:
  app:
    build: .
    tty: true
    env_file:
      - ./.env
    restart: unless-stopped
  voicebox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - '50021:50021'
    restart: unless-stopped
